### ISSUE TITLE
Proposal: Provide a common feature set for asset-pipeline-specific libraries 

### ISSUE THREAD

**Issue by BrianSipple** [svgstore/svgstore#1]
Hi Shannon, 

As of right now, there are (at least) four different projects implementing their own svgstore functionality: [grunt-svgstore](https://github.com/FWeinb/grunt-svgstore), [gulp-svgstore](https://github.com/w0rm/gulp-svgstore), [broccoli-svgstore](https://github.com/jmarquis/broccoli-svgstore), and [others](https://www.npmjs.com/search?q=svgstore) are all set up to operate within their own build systems, but they're also implementing their own logic for the same, conceptually identical task of parsing `<svg>` elements and writing them to a file of `<symbol>` defs. 

Furthermore, each project is taking it upon itself to implement support for options-based features such as 
[inline style removal](https://github.com/FWeinb/grunt-svgstore#optionscleanup-since-026). This is fantastic, but as I'm getting started on developing a new version of `broccoli-svgstore` and exploring ways to add similar functionality, I can't help but notice that we're all duplicating a lot of the same things. 

And so, it seems like there's a great opportunity to unify our efforts... to have one project -- this one, whose fundamental design principle is to be build system-agnostic -- abstract SVG parsing, and at the same handle (and thus, offer a common API for) the intricacies of inline style removal, [viewbox inheritance](https://github.com/FWeinb/grunt-svgstore#optionsinheritviewbox-since-040), [id-generation](https://github.com/FWeinb/grunt-svgstore#optionsconvertnametoid-since-040), and anything else we come up with. 

I'd love to help out as a contributor to such an effort. I'm wondering if you'd be on board, and I'd also love to hear ideas from collaborators on the svgstore projects mentioned above (cc @FWeinb, @w0rm).

Cheers!

**Comment by shannonmoeller** [comment]
I'm all for it and would be willing to transfer this repo to an `svgstore` github org so I'm not a bottleneck.

**Comment by ghost** [comment]
@shannonmoeller, @BrianSipple This looks great. I'd be happy to help out with this endeavor.

**Comment by shannonmoeller** [comment]
Org created and repo transferred.

**Comment by FWeinb** [comment]
I would like this too! I don't have much time to maintain `grunt-svgstore` anymore so an common set of features across various asset-pipelines sounds great! @jonathantneal was maintaining `grunt-svgstore` for a while now, so it would be good to get him involved if he wants to.

**Comment by BrianSipple** [comment]
Awesome! And @shannonmoeller, I don't think think you'd be a bottleneck at all. To the contrary, I'm seeing `svgstore` as the main utility that `broccoli-svgstore`, `grunt-svgstore`, etc could call from their respective writing functions, having, themselves, to only be concerned with providing the right source and formatting the right options hash.

I'll start manifesting a full list of options to potentially support as Github Issues, but a quick brain dump...
- [x] Inline style removal (#3)
- [x] Custom attribute preservation — defaulting to id, viewbox, role, and aria-labelledby (the latter two are hugely beneficial for [screen reader support](http://codepen.io/NathanPJF/details/GJObGm)) (#4, #13)
- [x] viewBox inheritance (#4, #13)
- [x] Custom id generation (#13)
- [ ] Indentation
- [ ] Fixed-size versions

**Comment by shannonmoeller** [comment]
@BrianSipple The last items on your checklist would be better as their own issues at this point. Would you be willing to split those off and close this issue, please?

**Comment by shannonmoeller** [comment]
@BrianSipple Regarding indentation, is that worth implementing at this level? Cherrio doesn't support formatted xml output so we'd have to pull in a prettifier which seems like a large dep for something optional. Seems like the build tasks and cli should handle that if it's wanted.

**Comment by BrianSipple** [comment]
@shannonmoeller Good point about indentation. I threw that in without really considering it, but I absolutely agree.

**Comment by BrianSipple** [comment]
Closing now after opening #14
